### ISSUE TITLE
Revert to blanket

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bip69#6]
I don't like waiting an hour to install all developer dependencies.
`blanket` is light weight,  and worked well with `travis-cov`.

I just want to know that all code paths are tested, if not, fail the tests.
After that,  I can look into it in more depth.

Why do we need coveralls and istanbul?

**Comment by fanatid** [comment]
Ref: https://github.com/bitcoinjs/bs58check/pull/8

**Comment by dcousens** [comment]
Never mind this issue.
Upon further testing,  I can't find any effective alternatives to `blanket` that also work with `tape`.
`nyc` works pretty damn well, (and overall, isn't as huge as I thought, compared) and I like the `--check-coverage` threshold options,  so I'm going to stick with it for now.
Thanks @fanatid :+1:
